version: '3.8'

services:
  sailtix-docs:
    build: .
    container_name: sailtix-docs
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
      - SESSION_DURATION_HOURS=24
      - MAX_LOGIN_ATTEMPTS=5
      - LOCKOUT_DURATION_MINUTES=15
    volumes:
      - ./config.json:/app/config.json:ro
      - ./agents.json:/app/agents.json:ro
      - ./openapi.yaml:/app/openapi.yaml:ro
      - ./openapi-v2.yaml:/app/openapi-v2.yaml:ro
    restart: unless-stopped
    networks:
      - sailtix-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for HTTPS
  nginx:
    image: nginx:alpine
    container_name: sailtix-docs-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - sailtix-docs
    restart: unless-stopped
    networks:
      - sailtix-network

networks:
  sailtix-network:
    driver: bridge 